# 주제 : 오늘 밤 유럽 축구, 어디가 이길까? 
----------
    
    
## 데이터 소개
    - 다음 1개의 sqlite 데이터베이스를 사용합니다.
    database.sqlite

    - 데이터 베이스 내 총 7개의 Table을 사용합니다.
    Country: 국가 정보
    League: 리그 정보
    Match: 경기 정보 (주 데이터셋)
    Player: 플레이어 정보
    Player_Attributes: 플레이어의 특성
    Team: 팀 정보
    Team_Attributes: 팀의 특성
    
- 데이터 출처: https://www.kaggle.com/hugomathien/soccer

## Step 1. 데이터셋 준비하기

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

### 1-1 Kaggle API 세팅하기.

In [2]:
import os

In [3]:
# os.environ을 이용하여 Kaggle API Username, Key 세팅하기
KAGGLE_USERNAME = pickle.load(open('./KAGGLE_USERNAME.plk','rb'))
KAGGLE_KEY = pickle.load(open('./KAGGLE_KEY.plk','rb'))

os.environ['KAGGLE_USERNAME'] = KAGGLE_USERNAME
os.environ['KAGGLE_KEY'] = KAGGLE_KEY

### 1-2 데이터 다운로드 및 압축 해제하기.

In [13]:
# Linux 명령어로 Kaggle API를 이용하여 데이터셋 다운로드하기 (!kaggle ~)
# Linux 명령어로 압축 해제하기
!kaggle datasets download -d hugomathien/soccer
!mkdir ./input_4/
!unzip *.zip -d ./input_4/
!rm *.zip

Downloading soccer.zip to /Users/s107166/Desktop/Project/Python_Project/Python_Basic
 98%|█████████████████████████████████████▏| 32.0M/32.7M [00:03<00:00, 10.9MB/s]
100%|██████████████████████████████████████| 32.7M/32.7M [00:03<00:00, 9.91MB/s]
Archive:  soccer.zip
  inflating: ./input_4/database.sqlite

In [4]:
!ls ./input_4/

database.sqlite

### 1-3 sqlite3와 Pandas로 sqlite 데이터베이스 읽어들이기

In [5]:
import sqlite3

In [8]:
# sqlite3.connect()와 pd.read_sql_query()로 csv파일 읽어들이기
conn = sqlite3.connect('./input_4/database.sqlite')
df_country = pd.read_sql_query('SELECT * FROM country',conn)
df_league = pd.read_sql_query('SELECT * FROM league',conn)
df_match = pd.read_sql_query('SELECT * FROM match',conn)
df_player = pd.read_sql_query('SELECT * FROM player',conn)
df_player_att = pd.read_sql_query('SELECT * FROM player_attributes',conn)
df_team = pd.read_sql_query('SELECT * FROM team', conn)
df_team_att = pd.read_sql_query('SELECT * FROM team_attributes', conn)

## Step 2. EDA 및 데이터 기초 통계 분석

### 2-1 각 데이터프레임의 구조 파악하기

In [19]:
# DataFrame에서 제공하는 메소드를 이용하여 각 데이터프레임의 구조 분석하기 (head(), info(), describe())

df_country.tail()

       id         name
6   15722       Poland
7   17642     Portugal
8   19694     Scotland
9   21518        Spain
10  24558  Switzerland

In [23]:
df_country['id'].unique()

array([    1,  1729,  4769,  7809, 10257, 13274, 15722, 17642, 19694,
       21518, 24558])

In [18]:
df_league.tail()

       id  country_id                      name
6   15722       15722        Poland Ekstraklasa
7   17642       17642  Portugal Liga ZON Sagres
8   19694       19694   Scotland Premier League
9   21518       21518           Spain LIGA BBVA
10  24558       24558  Switzerland Super League

In [24]:
df_league['id'].unique()

array([    1,  1729,  4769,  7809, 10257, 13274, 15722, 17642, 19694,
       21518, 24558])

In [20]:
df_match.tail()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df_match.loc[df_match['league_id']==10257]

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
10256,10257,10257,10257,2008/2009,1,2008-08-31 00:00:00,537632,8524,8551,1,...,4.33,2.00,3.0,3.50,2.00,3.0,4.0,1.83,3.0,4.20
10257,10258,10257,10257,2008/2009,1,2008-08-31 00:00:00,537633,8529,8543,1,...,2.70,3.00,2.8,2.40,2.70,3.0,2.6,2.50,3.0,2.62
10258,10259,10257,10257,2008/2009,1,2008-08-31 00:00:00,537634,8530,10233,1,...,3.40,2.30,3.0,3.00,2.40,2.9,3.0,2.30,3.0,2.88
10259,10260,10257,10257,2008/2009,1,2008-08-31 00:00:00,537635,8533,8690,2,...,3.50,2.00,3.0,3.50,2.15,3.0,3.4,2.10,3.0,3.25
10260,10261,10257,10257,2008/2009,1,2008-08-31 00:00:00,537636,8535,9885,1,...,2.80,2.60,3.0,2.60,2.70,3.0,2.6,2.50,3.0,2.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13268,13269,10257,10257,2015/2016,9,2015-10-25 00:00:00,2060429,8543,9804,3,...,NaN,1.93,3.4,4.75,NaN,NaN,NaN,NaN,NaN,NaN
13269,13270,10257,10257,2015/2016,9,2015-10-25 00:00:00,2060430,8564,7943,2,...,NaN,1.80,3.7,5.00,NaN,NaN,NaN,NaN,NaN,NaN
13270,13271,10257,10257,2015/2016,9,2015-10-24 00:00:00,2060431,8540,8636,1,...,NaN,4.00,3.4,2.10,NaN,NaN,NaN,NaN,NaN,NaN
13271,13272,10257,10257,2015/2016,9,2015-10-25 00:00:00,2060432,9882,9876,4,...,NaN,2.05,3.4,4.10,NaN,NaN,NaN,NaN,NaN,NaN
13272,13273,10257,10257,2015/2016,9,2015-10-25 00:00:00,2060433,8600,9891,1,...,NaN,1.70,3.8,5.75,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
for c in df_match.columns:
    print(c)

id
country_id
league_id
season
stage
date
match_api_id
home_team_api_id
away_team_api_id
home_team_goal
away_team_goal
home_player_X1
home_player_X2
home_player_X3
home_player_X4
home_player_X5
home_player_X6
home_player_X7
home_player_X8
home_player_X9
home_player_X10
home_player_X11
away_player_X1
away_player_X2
away_player_X3
away_player_X4
away_player_X5
away_player_X6
away_player_X7
away_player_X8
away_player_X9
away_player_X10
away_player_X11
home_player_Y1
home_player_Y2
home_player_Y3
home_player_Y4
home_player_Y5
home_player_Y6
home_player_Y7
home_player_Y8
home_player_Y9
home_player_Y10
home_player_Y11
away_player_Y1
away_player_Y2
away_player_Y3
away_player_Y4
away_player_Y5
away_player_Y6
away_player_Y7
away_player_Y8
away_player_Y9
away_player_Y10
away_player_Y11
home_player_1
home_player_2
home_player_3
home_player_4
home_player_5
home_player_6
home_player_7
home_player_8
home_player_9
home_player_10
home_player_11
away_player_1
away_player_2
away_player_3
away_player_4
away_player_5
away_player_6
away_player_7
away_player_8
away_player_9
away_player_10
away_player_11
goal
shoton
shotoff
foulcommit
card
cross
corner
possession
B365H
B365D
B365A
BWH
BWD
BWA
IWH
IWD
IWA
LBH
LBD
LBA
PSH
PSD
PSA
WHH
WHD
WHA
SJH
SJD
SJA
VCH
VCD
VCA
GBH
GBD
GBA
BSH
BSD
BSA

In [31]:
df_match.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25979 entries, 0 to 25978
Columns: 115 entries, id to BSA
dtypes: float64(96), int64(9), object(10)
memory usage: 22.8+ MB

In [33]:
df_match.isna()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
25975,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
25976,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
25977,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
25978,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True

In [34]:
df_match.isna().sum()

id                0
country_id        0
league_id         0
season            0
stage             0
              ...
GBD           11817
GBA           11817
BSH           11818
BSD           11818
BSA           11818
Length: 115, dtype: int64

In [35]:
for c in df_match.isna().sum():
    print(c)

0
0
0
0
0
0
0
0
0
0
0
1821
1821
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1833
1833
1839
1821
1821
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1832
1833
1833
1839
1224
1315
1281
1323
1316
1325
1227
1309
1273
1436
1555
1234
1278
1293
1321
1335
1313
1235
1341
1328
1441
1554
11762
11762
11762
11762
11762
11762
11762
11762
3387
3387
3387
3404
3404
3404
3459
3459
3459
3423
3423
3423
14811
14811
14811
3408
3408
3408
8882
8882
8882
3411
3411
3411
11817
11817
11817
11818
11818
11818

In [36]:
for c, num in zip(df_match.columns, df_match.isna().sum()):
    print(c, num)

id 0
country_id 0
league_id 0
season 0
stage 0
date 0
match_api_id 0
home_team_api_id 0
away_team_api_id 0
home_team_goal 0
away_team_goal 0
home_player_X1 1821
home_player_X2 1821
home_player_X3 1832
home_player_X4 1832
home_player_X5 1832
home_player_X6 1832
home_player_X7 1832
home_player_X8 1832
home_player_X9 1832
home_player_X10 1832
home_player_X11 1832
away_player_X1 1832
away_player_X2 1832
away_player_X3 1832
away_player_X4 1832
away_player_X5 1832
away_player_X6 1832
away_player_X7 1832
away_player_X8 1832
away_player_X9 1833
away_player_X10 1833
away_player_X11 1839
home_player_Y1 1821
home_player_Y2 1821
home_player_Y3 1832
home_player_Y4 1832
home_player_Y5 1832
home_player_Y6 1832
home_player_Y7 1832
home_player_Y8 1832
home_player_Y9 1832
home_player_Y10 1832
home_player_Y11 1832
away_player_Y1 1832
away_player_Y2 1832
away_player_Y3 1832
away_player_Y4 1832
away_player_Y5 1832
away_player_Y6 1832
away_player_Y7 1832
away_player_Y8 1832
away_player_Y9 1833
away_player_Y10 1833
away_player_Y11 1839
home_player_1 1224
home_player_2 1315
home_player_3 1281
home_player_4 1323
home_player_5 1316
home_player_6 1325
home_player_7 1227
home_player_8 1309
home_player_9 1273
home_player_10 1436
home_player_11 1555
away_player_1 1234
away_player_2 1278
away_player_3 1293
away_player_4 1321
away_player_5 1335
away_player_6 1313
away_player_7 1235
away_player_8 1341
away_player_9 1328
away_player_10 1441
away_player_11 1554
goal 11762
shoton 11762
shotoff 11762
foulcommit 11762
card 11762
cross 11762
corner 11762
possession 11762
B365H 3387
B365D 3387
B365A 3387
BWH 3404
BWD 3404
BWA 3404
IWH 3459
IWD 3459
IWA 3459
LBH 3423
LBD 3423
LBA 3423
PSH 14811
PSD 14811
PSA 14811
WHH 3408
WHD 3408
WHA 3408
SJH 8882
SJD 8882
SJA 8882
VCH 3411
VCD 3411
VCA 3411
GBH 11817
GBD 11817
GBA 11817
BSH 11818
BSD 11818
BSA 11818

In [40]:
df_match.columns[77:]

Index(['goal', 'shoton', 'shotoff', 'foulcommit', 'card', 'cross', 'corner',
       'possession', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH',
       'IWD', 'IWA', 'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD',
       'WHA', 'SJH', 'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'GBH', 'GBD', 'GBA',
       'BSH', 'BSD', 'BSA'],
      dtype='object')

In [41]:
df_match.drop(df_match.columns[77:], axis=1,inplace=True)

In [42]:
df_match.head()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df_player.head()

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154

In [44]:
df_player_att.head()

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [45]:
df_team.head()

   id  team_api_id  team_fifa_api_id     team_long_name team_short_name
0   1         9987             673.0           KRC Genk             GEN
1   2         9993             675.0       Beerschot AC             BAC
2   3        10000           15005.0   SV Zulte-Waregem             ZUL
3   4         9994            2007.0   Sporting Lokeren             LOK
4   5         9984            1750.0  KSV Cercle Brugge             CEB

In [48]:
df_team['team_short_name'].count()

299

In [49]:
df_team['team_api_id'].count()

299

In [50]:
df_team_att.head()

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,1,434,9930,2010-02-22 00:00:00,60,Balanced,NaN,Little,50,Mixed,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
1,2,434,9930,2014-09-19 00:00:00,52,Balanced,48.0,Normal,56,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,3,434,9930,2015-09-10 00:00:00,47,Balanced,41.0,Normal,54,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,4,77,8485,2010-02-22 00:00:00,70,Fast,NaN,Little,70,Long,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,5,77,8485,2011-02-22 00:00:00,47,Balanced,NaN,Little,52,Mixed,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover

### 2-2 데이터프레임간의 관계 파악하기

In [ ]:
# 데이터프레임 간 중복되는 Column이 있는지 확인하고 유용한 Column 식별하기
# Hint) unique()로 값을 비교하거나, map() 등을 활용하여 Column 관계를 확인

### 2-3 선수 특성 사이의 상관성 파악하기

In [ ]:
# DataFrame의 corr() 메소드와 Seaborn의 heatmap() 메소드를 이용하여 Pearson's correlation 시각화하기

### 2-4 매치 데이터프레임에 팀 특성 데이터프레임 통합하기

In [ ]:
# DataFrame의 map() 메소드를 활용하여 데이터프레임 통합하기

### 2-5 홈과 어웨이의 골 수를 승-무-패 범주로 변환하기

In [ ]:
# 홈과 어웨이의 골 수를 범주형 데이터로 변환하기 (0: 홈팀 승, 1: 무승부, 2: 어웨이팀 승)



df['matchResult'] =

## Step 3. 모델 학습을 위한 데이터 전처리

### 3-1 get_dummies를 이용하여 범주형 데이터 전처리하기

### 3-2 StandardScaler를 이용해 수치형 데이터 표준화하기

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
# StandardScaler를 이용해 수치형 데이터를 표준화하기
# Hint) Multicollinearity를 피하기 위해 불필요한 컬럼은 drop한다.

X_num = 
X_cat =
X = 
y = df_match['matchResult']

### 3-3 학습데이터와 테스트데이터 분리하기

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# train_test_split() 함수로 학습 데이터와 테스트 데이터 분리하기
X_train, X_test, y_train, y_test =

## Step 4. Classification 모델 학습하기

### 4-1 Logistic Regression 모델 생성/학습하기

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
# LogisticRegression 모델 생성/학습
model_lr =

### 4-2 모델 학습 결과 평가하기

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
# Predict를 수행하고 classification_report() 결과 출력하기
pred =

### 4-3 XGBoost 모델 생성/학습하기

In [ ]:
from xgboost import XGBClassifier

In [ ]:
# XGBClassifier 모델 생성/학습
model_xgb =

### 4-4 모델 학습 결과 평가하기

In [ ]:
# Predict를 수행하고 classification_report() 결과 출력하기
pred =

## Step5 모델 학습 결과 심화 분석하기

### 5-1 Logistic Regression 모델 계수로 상관성 파악하기

In [ ]:
# Logistic Regression 모델의 coef_ 속성을 plot하기

### 5-2 XGBoost 모델로 특징의 중요도 확인하기

In [ ]:
# XGBoost 모델의 feature_importances_ 속성을 plot하기

## Step6 모델 성능 개선하기

### 6-1 매치 데이터프레임에 선수 특성 데이터프레임 통합하기

In [ ]:
# 선수 특성 중 유의미한 정보를 매치 데이터프레임에 통합하기

### 6-2 모델 재학습하여 평가하기